import Paper from '@mui/material/Paper';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Alert from '@mui/material/Alert';
import Chip from '@mui/material/Chip';
import CircularProgress from '@mui/material/CircularProgress';
import Stack from '@mui/material/Stack';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import ReplayIcon from '@mui/icons-material/Replay';
import ReactMarkdown from 'react-markdown';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getInterpretation, requestInterpretation } from '../api/reports';
import type { LlmInterpretation } from '../api/types';

export function AiInterpretationPanel({ reportId }: { reportId: string }) {
  const queryClient = useQueryClient();

  const existing = useQuery({
    queryKey: ['interpretation', reportId],
    queryFn: () => getInterpretation(reportId),
  });

  const mutation = useMutation({
    mutationFn: (refresh: boolean) => requestInterpretation(reportId, refresh),
    onSuccess: (data) => queryClient.setQueryData(['interpretation', reportId], data),
  });

  const interpretation: LlmInterpretation | null | undefined = mutation.data ?? existing.data;
  const loading = mutation.isPending;

  return (
    <Paper sx={{ p: 2.5 }}>
      <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 1.5 }}>
        <AutoAwesomeIcon color="primary" />
        <Typography variant="h6" sx={{ flexGrow: 1 }}>
          AI preliminary interpretation
        </Typography>
        {interpretation?.model && <Chip size="small" label={interpretation.model} />}
      </Stack>

      <Alert severity="info" sx={{ mb: 2 }}>
        Preliminary, AI-generated decision support — <strong>not a diagnosis</strong>. A physician
        must review and confirm. Patient identifiers are never sent to the AI model.
      </Alert>

      {mutation.isError && (
        <Alert severity="error" sx={{ mb: 2 }}>
          The AI assistant is currently unavailable. Please try again.
        </Alert>
      )}

      {loading && (
        <Stack direction="row" spacing={2} alignItems="center" sx={{ py: 3 }}>
          <CircularProgress size={22} />
          <Typography color="text.secondary">
            Generating… inference runs locally on CPU and may take ~10–60 seconds.
          </Typography>
        </Stack>
      )}

      {!loading && interpretation?.responseText && (
        <Box sx={{ '& p': { mt: 0.5, mb: 1 }, '& ul': { mt: 0.5, mb: 1, pl: 3 } }}>
          <ReactMarkdown>{interpretation.responseText}</ReactMarkdown>
          <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 2 }}>
            Generated by {interpretation.createdBy ?? 'system'}
            {interpretation.latencyMs != null && ` · ${(interpretation.latencyMs / 1000).toFixed(1)}s`}
            {interpretation.createdAt && ` · ${new Date(interpretation.createdAt).toLocaleString()}`}
          </Typography>
        </Box>
      )}

      {!loading && (
        <Box sx={{ mt: 1 }}>
          <Button
            variant={interpretation ? 'outlined' : 'contained'}
            startIcon={interpretation ? <ReplayIcon /> : <AutoAwesomeIcon />}
            onClick={() => mutation.mutate(Boolean(interpretation))}
            disabled={existing.isLoading}
          >
            {interpretation ? 'Regenerate' : 'Get AI interpretation'}
          </Button>
        </Box>
      )}
    </Paper>
  );
}
